BEGIN;

DROP TABLE IF EXISTS CleaningTaskTemplateListToCleaningTaskTemplate CASCADE;
DROP TABLE IF EXISTS CleaningTaskTemplate CASCADE;
DROP TABLE IF EXISTS CleaningTaskTemplateList CASCADE;
DROP TABLE IF EXISTS CleaningTask CASCADE;
DROP TABLE IF EXISTS Area CASCADE;
DROP TABLE IF EXISTS CleaningTaskList CASCADE;

COMMIT;